create sequence hibernate_sequence start 1 increment 1;

create table if not exists public.student
(
	id bigint generated by default as identity
		constraint student_pkey
			primary key,
	birth_date date,
	first_name varchar(255),
	gender integer,
	last_name varchar(255),
	activity_id bigint
		constraint fkooscbac9cnh88ag4a81ikfmvw
			references public.activity,
	group_id bigint
		constraint fkd2slqqxxl5g1axj5th1nqukq7
			references public."group"
);


create table public."group"
(
    id          bigint generated by default as identity
        constraint group_pkey
            primary key,
    description varchar(255),
    title       varchar(255)
);


create table public.activity
(
    id              bigint generated by default as identity (maxvalue 2147483647)
        constraint activity_pkey
            primary key,
    audience_number bigint,
    title           varchar(255),
    end_time        time,
    start_time      time
);