create table if not exists activity
(
	id bigint generated by default as identity
		constraint activity_pkey
			primary key,
	audience_number bigint,
	end_time time,
	start_time time,
	title varchar(255)
);

alter table activity owner to "learning-db";

create table if not exists "group"
(
	id bigint generated by default as identity
		constraint group_pkey
			primary key,
	description varchar(255),
	title varchar(255),
	activity_id bigint
		constraint fk82c7n8i5tev6rrtxxat8w2s52
			references activity
);

alter table "group" owner to "learning-db";

create table if not exists student
(
	id bigint generated by default as identity
		constraint student_pkey
			primary key,
	birth_date date,
	first_name varchar(255),
	gender integer,
	last_name varchar(255),
	group_id bigint
		constraint fkd2slqqxxl5g1axj5th1nqukq7
			references "group"
);

alter table student owner to "learning-db";

